openapi: 3.0.3
info:
  title: Shopping_cart
  version: 1.0.0
  contact: {}
servers:
- url: /
paths:
  /cart/user/{user_id}/:
    get:
      tags:
      - cart
      - user/{user_id}
      summary: Получить корзину по id пользователя
      description: Получить корзину по id пользователя
      operationId: id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: <integer>
                    product_amount:
                      type: number
                      example: 1
                    product_id:
                      type: string
                      example: <string>
                    user_id:
                      type: string
                      example: <integer>
                example:
                - id: <integer>
                  product_amount: 1
                  product_id: <string>
                  user_id: <integer>
                - id: <integer>
                  product_amount: 1
                  product_id: <string>
                  user_id: <integer>
              examples:
                Successful Response:
                  value:
                  - id: <integer>
                    product_amount: 1
                    product_id: <string>
                    user_id: <integer>
                  - id: <integer>
                    product_amount: 1
                    product_id: <string>
                    user_id: <integer>
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                            example: <string>
                          example:
                          - <string>
                          - <string>
                        msg:
                          type: string
                          example: <string>
                        type:
                          type: string
                          example: <string>
                    example:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
              examples:
                Validation Error:
                  value:
                    detail:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
    delete:
      tags:
      - cart
      - user/{user_id}
      summary: Удалить корзину по id пользователя
      description: Удалить корзину по id пользователя
      operationId: id1
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Successful Response:
                  value: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                            example: <string>
                          example:
                          - <string>
                          - <string>
                        msg:
                          type: string
                          example: <string>
                        type:
                          type: string
                          example: <string>
                    example:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
              examples:
                Validation Error:
                  value:
                    detail:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type: string
        example: <integer>
      description: '(Required) '
  /cart/:
    get:
      tags:
      - cart
      summary: Получить список всех записей
      description: Получить список всех записей
      operationId: '1'
      parameters:
      - name: limit
        in: query
        schema:
          type: string
          example: '100'
      - name: start_pos
        in: query
        schema:
          type: string
          example: '0'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: <integer>
                    product_amount:
                      type: number
                      example: 1
                    product_id:
                      type: string
                      example: <string>
                    user_id:
                      type: string
                      example: <integer>
                example:
                - id: <integer>
                  product_amount: 1
                  product_id: <string>
                  user_id: <integer>
                - id: <integer>
                  product_amount: 1
                  product_id: <string>
                  user_id: <integer>
              examples:
                Successful Response:
                  value:
                  - id: <integer>
                    product_amount: 1
                    product_id: <string>
                    user_id: <integer>
                  - id: <integer>
                    product_amount: 1
                    product_id: <string>
                    user_id: <integer>
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                            example: <string>
                          example:
                          - <string>
                          - <string>
                        msg:
                          type: string
                          example: <string>
                        type:
                          type: string
                          example: <string>
                    example:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
              examples:
                Validation Error:
                  value:
                    detail:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
    post:
      tags:
      - cart
      summary: Добавить товар в корзину (создать запись)
      description: Добавить товар в корзину (создать запись)
      operationId: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_amount:
                  type: number
                  example: 1
                product_id:
                  type: string
                  example: <string>
                user_id:
                  type: string
                  example: <integer>
            examples:
              Добавить товар в корзину (создать запись):
                value:
                  product_amount: 1
                  product_id: <string>
                  user_id: <integer>
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: <integer>
                  product_amount:
                    type: number
                    example: 1
                  product_id:
                    type: string
                    example: <string>
                  user_id:
                    type: string
                    example: <integer>
              examples:
                Successful Response:
                  value:
                    id: <integer>
                    product_amount: 1
                    product_id: <string>
                    user_id: <integer>
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                            example: <string>
                          example:
                          - <string>
                          - <string>
                        msg:
                          type: string
                          example: <string>
                        type:
                          type: string
                          example: <string>
                    example:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
              examples:
                Validation Error:
                  value:
                    detail:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
  /cart/{id}:
    delete:
      tags:
      - cart
      summary: Удалить запись по id
      description: Удалить запись по id
      operationId: id2
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Successful Response:
                  value: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                            example: <string>
                          example:
                          - <string>
                          - <string>
                        msg:
                          type: string
                          example: <string>
                        type:
                          type: string
                          example: <string>
                    example:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
              examples:
                Validation Error:
                  value:
                    detail:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: <integer>
      description: '(Required) '
  /cart/product/{product_id}/:
    delete:
      tags:
      - cart
      summary: Удалить записи по id товара
      description: Удалить записи по id товара
      operationId: id3
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Successful Response:
                  value: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                            example: <string>
                          example:
                          - <string>
                          - <string>
                        msg:
                          type: string
                          example: <string>
                        type:
                          type: string
                          example: <string>
                    example:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
              examples:
                Validation Error:
                  value:
                    detail:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
    parameters:
    - name: product_id
      in: path
      required: true
      schema:
        type: string
        example: <string>
      description: '(Required) '
tags:
- name: cart
- name: user/{user_id}

