services:
  user:
    build:
      context: .
      dockerfile: user/Dockerfile
    container_name: user-service
    environment:
      - "POSTGRES_URI=postgres:5432"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASS=changeme"
      - "SECRET_JWT=TvNhr5INabwoWe8JfYvpRXKdQfCD9gmHtTbWzoOfhnI"
      - "REDIS_URI=redis:6379"
    ports:
      - "8000:8000"
  showcase:
    build:
      context: .
      dockerfile: showcase/Dockerfile
    container_name: showcase-service
    environment:
      - "MONGO_URI=mongodb://mongo:27017/"
      - "DB_NAME=online-shop"
      - "SECRET_JWT=TvNhr5INabwoWe8JfYvpRXKdQfCD9gmHtTbWzoOfhnI"
    ports:
      - "8001:8000"
  shopping_cart:
    build:
      context: .
      dockerfile: shopping_cart/Dockerfile
    container_name: shopping_cart-service
    environment:
      - "POSTGRES_URI=postgres:5432"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASS=changeme"
      - "SECRET_JWT=TvNhr5INabwoWe8JfYvpRXKdQfCD9gmHtTbWzoOfhnI"
    ports:
      - "8002:8000"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: online_shop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/redis

volumes:
  pgdata:
  mongodata:
  redisdata: