openapi: 3.0.3
info:
  title: Showcase
  version: 1.0.0
  contact: {}
servers:
- url: /
paths:
  /clothes/{id}:
    get:
      tags:
      - clothes
      - '{id}'
      summary: Получить предмет одежды по id
      description: Получить предмет одежды по id
      operationId: id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: <string>
                  colour:
                    type: string
                    example: <string>
                  name:
                    type: string
                    example: <string>
                  type:
                    type: string
                    example: <string>
              examples:
                Successful Response:
                  value:
                    _id: <string>
                    colour: <string>
                    name: <string>
                    type: <string>
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                            example: <string>
                          example:
                          - <string>
                          - <string>
                        msg:
                          type: string
                          example: <string>
                        type:
                          type: string
                          example: <string>
                    example:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
              examples:
                Validation Error:
                  value:
                    detail:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
    delete:
      tags:
      - clothes
      - '{id}'
      summary: Удалить предмет одежды по id
      description: Удалить предмет одежды по id
      operationId: id2
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Successful Response:
                  value: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                            example: <string>
                          example:
                          - <string>
                          - <string>
                        msg:
                          type: string
                          example: <string>
                        type:
                          type: string
                          example: <string>
                    example:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
              examples:
                Validation Error:
                  value:
                    detail:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
    patch:
      tags:
      - clothes
      - '{id}'
      summary: Изменить предмет одежды по id
      description: Изменить предмет одежды по id
      operationId: id1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                colour:
                  type: string
                  example: <string>
                name:
                  type: string
                  example: <string>
                type:
                  type: string
                  example: <string>
            examples:
              Изменить предмет одежды по id:
                value:
                  colour: <string>
                  name: <string>
                  type: <string>
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                Successful Response:
                  value: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                            example: <string>
                          example:
                          - <string>
                          - <string>
                        msg:
                          type: string
                          example: <string>
                        type:
                          type: string
                          example: <string>
                    example:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
              examples:
                Validation Error:
                  value:
                    detail:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
        example: <string>
      description: '(Required) '
  /clothes/:
    get:
      tags:
      - clothes
      summary: Получить список всех предметов одежды
      description: Получить список всех предметов одежды
      operationId: '1'
      parameters:
      - name: limit
        in: query
        schema:
          type: string
          example: '100'
      - name: start_pos
        in: query
        schema:
          type: string
          example: '0'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: <string>
                    colour:
                      type: string
                      example: <string>
                    name:
                      type: string
                      example: <string>
                    type:
                      type: string
                      example: <string>
                example:
                - _id: <string>
                  colour: <string>
                  name: <string>
                  type: <string>
                - _id: <string>
                  colour: <string>
                  name: <string>
                  type: <string>
              examples:
                Successful Response:
                  value:
                  - _id: <string>
                    colour: <string>
                    name: <string>
                    type: <string>
                  - _id: <string>
                    colour: <string>
                    name: <string>
                    type: <string>
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                            example: <string>
                          example:
                          - <string>
                          - <string>
                        msg:
                          type: string
                          example: <string>
                        type:
                          type: string
                          example: <string>
                    example:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
              examples:
                Validation Error:
                  value:
                    detail:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
    post:
      tags:
      - clothes
      summary: Создать новый предмет одежды
      description: Создать новый предмет одежды
      operationId: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                colour:
                  type: string
                  example: <string>
                name:
                  type: string
                  example: <string>
                type:
                  type: string
                  example: <string>
            examples:
              Создать новый предмет одежды:
                value:
                  colour: <string>
                  name: <string>
                  type: <string>
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                    example: <string>
                  colour:
                    type: string
                    example: <string>
                  name:
                    type: string
                    example: <string>
                  type:
                    type: string
                    example: <string>
              examples:
                Successful Response:
                  value:
                    _id: <string>
                    colour: <string>
                    name: <string>
                    type: <string>
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: array
                    items:
                      type: object
                      properties:
                        loc:
                          type: array
                          items:
                            type: string
                            example: <string>
                          example:
                          - <string>
                          - <string>
                        msg:
                          type: string
                          example: <string>
                        type:
                          type: string
                          example: <string>
                    example:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
              examples:
                Validation Error:
                  value:
                    detail:
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
                    - loc:
                      - <string>
                      - <string>
                      msg: <string>
                      type: <string>
tags:
- name: clothes
- name: '{id}'

